### ISSUE TITLE
Option to use TESS-SPOC lightcurves

### ISSUE THREAD

**Issue by gdransfield** [franpoz/SHERLOCK#106]
Hi!

I'm wondering if we could have the option to use different pipelines for long cadence targets. It seems only Eleanor is used for these, but sometimes QLP or TESS-SPOC lightcurves are available and they are often better.

Cheers,
George

**Comment by martindevora** [comment]
Hello.

I've been wondering for a while about how to provide a smoother way to retrieve the data independently from the provider. Your requirement aligns well with it. The only negative point is that it will probably require a deep refactoring of the current code.

I will come back with something. Keep posted!

Regards.

**Comment by martindevora** [comment]
Already implemented!
