### ISSUE TITLE
[Bug] in reporting border score 

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#44]
When running the TIC 467179258, in the 3rd run is detected a signal which all the detected transits are in borders. However, the border score indicates that they are not (Border score=1). 
This needs further exploration. 

![Run_3_PDCSAP-FLUX_MIS_TIC 467179528_all](https://user-images.githubusercontent.com/15654884/92958451-9020c980-f46a-11ea-8a80-afa822699459.png)

```
win_size    Period    Per_err   N.Tran  Mean Depth (ppt)  T. dur (min)  T0            SNR           SDE           FAP           Border_score      
PDCSAP_FLUX 32.01687  0.104577  1       1.899             138.0         1710.2785     8.614         24.781        8.0032e-05    1.00 


```

**Comment by martindevora** [comment]
We are not sure about this being a bug. It could be that the transit appears to be in the borders visually but if we focused on the signal we could appreciate that it is not.

**Comment by martindevora** [comment]
I reviewed this and can confirm that the transit was not in the borde, thoygh it was near to be there.
