### ISSUE TITLE
Modify the layout of the detrend plots

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#45]
The current layout of the detrends applied is not very useful when many sectors are available, even worse if the sectors are separated. For example: 

![Detrends_run_1_MIS_TIC 467179528_all](https://user-images.githubusercontent.com/15654884/92959623-71233700-f46c-11ea-882a-2dcb86b98296.png)

We should think about a more friendly-read layout. For example: 

![n=10_TIC_57984826_Sp0020+3305](https://user-images.githubusercontent.com/15654884/92959803-c4958500-f46c-11ea-8b7e-1909ee2674ca.png)

**Comment by martindevora** [comment]
I've been thinking a little bit about this. I'm not sure about a proper way of presenting the detrends in only one image. If the image size (height) is not constrained we could just always show all the detrends in an [n rows - 1 column] format. What do you think @franpoz ? If not, the only way I can imagine right now is by generating several detrends images containing a subset of detrends each.
