### ISSUE TITLE
Flexible exploration of detrend parameters: WS and KS

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#64]
We are using two detrends algorithms from` WOTAN` : bi-weight and Gaussian Process with Matern kernel 3/2. The most dramatic parameter is the window size (WS) and the kernel size (KS), respectively, which determine the length of the trend. Each detrend used by `SHERLOCK` make use of a different WS or KS. The minimum and maximum sizes are computed automatically as 3xT14 of an Earth planet in an orbit of 10 days and 20 times this value. However, the user may want to explore manually these values. 

Let's include in the parameters.yaml all these parameters.

**Comment by martindevora** [comment]
Done. We need examples.

**Comment by martindevora** [comment]
Done.
