### ISSUE TITLE
Add observation plan data after fit

### ISSUE THREAD

**Issue by martindevora** [franpoz/SHERLOCK#80]
It might be useful to create an observation planning tool at the end of the pipeline. We could give:
Observatory altitude, latitude and longitude. Additionally we could provide a range of dates and the number of observations that we would like to do.
We would need to see, as an output:
- Observation ephemeris (T0, ingress and egress) with uncertainties calculated from T = T0 + n*P.

**Comment by franpoz** [comment]
Correct uncertainties for `detal_T = sqrt(delta_T0**2+(n*delta_P)**2)`

**Comment by martindevora** [comment]
Already implemented. The output is given aas a csv. We don't close the issue yet as we'd like to provide a PDF too.
