### ISSUE TITLE
TPF plot  

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#98]
The last version of SHERLOCK has again the problem with the colors when representing the GAIA stars around. It uses a red-palette which makes difficult to see the stars. Moreover, the label of the bar is cut. Here an example: 

![Screenshot from 2021-04-11 13-49-26](https://user-images.githubusercontent.com/15654884/114303140-dc012300-9acc-11eb-9214-967b02482c0d.png)

**Comment by martindevora** [comment]
It should be fixed now.
