### ISSUE TITLE
Improving the FIT 

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#99]
A typical fit with SHERLOCK (via allesfitter) looks like that: 

![Screenshot from 2021-04-11 13-53-47](https://user-images.githubusercontent.com/15654884/114303244-73ff0c80-9acd-11eb-8d12-65411eecea06.png)

Here it can be seen that rr and rr_suma parameters are not correctly explored. This issue is coming from the injected values imported by TLS, which is using the maximum depth of the full set of transits, which is unrealistic. Hence, a better estimation for these two parameters: 

1) Use of the mean of the trantist depths 
2) uncertainties x 2 to provide a larger distribution to sample 

The red noise can be modeled using a GP Matern 3/2, whose hyperparameter at this point are not correctly sampled and they never converge (last two rows in the image above). To solve this we may use the noise estimation via allesfitter: 

```
import allesfitter
#MCMC - evaluation of the noise out of transit
allesfitter.estimate_noise_out_of_transit(datadir)
allesfitter.mcmc_output('allesfit')
#NS - we propagate the noise in transit
allesfitter.show_initial_guess('allesfit')
allesfitter.ns_fit('allesfit')
allesfitter.ns_output('allesfit')
```
Then, transits are masked (8h around each) and the perform an MCMC fitting the hyperparameters: 

![Screenshot from 2021-04-11 14-05-21](https://user-images.githubusercontent.com/15654884/114303571-18ce1980-9acf-11eb-9d9f-26cfbe1842f7.png)

These values can be used now in the fitting. Since we are providing with a relatively fast and accurate fitting, we may fix these values and not fit anymore when fitting the transits. 

As a final touch we may include a fitting in the LD coefficients q1 and q2, performing a sampling from 0 to 1. 

This would be the most efficient fitting to trigger a ground-base follow up

**Comment by martindevora** [comment]
Done, but the red noise previous fit won't be done.
